version: '3'
services:
  node:
    build:
      context: .
      dockerfile: ./prod/Dockerfile.prod
    env_file: ./.env.prod
    container_name: sateamapi
    tty: true
    stdin_open: true
    volumes:
      - ./dist:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    restart: always
    command: node -r dotenv/config index.js
    expose:
      - 4001
    # network_mode: webproxy
# networks:
#  default:
#    external:
#      name: webproxy
